<?php

namespace Database\Seeders;

use App\Models\Game;
use Illuminate\Database\Seeder;

class GameSeeder extends Seeder
{
    public function run(): void
    {
        $games = [
            [
                'title' => 'Cyberpunk 2077',
                'description' => 'Un RPG de acción en mundo abierto ambientado en la megalópolis Night City, donde el poder, el glamour y las modificaciones corporales conviven con la violencia.',
                'developer' => 'CD Projekt Red',
                'publisher' => 'CD Projekt',
                'price' => 39.99,
                'genres' => ['RPG', 'Action', 'Open World'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox'],
                'release_date' => '2020-12-10',
                'metacritic_score' => 86,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg',
            ],
            [
                'title' => 'The Witcher 3: Wild Hunt',
                'description' => 'Eres Geralt de Rivia, un cazarrecompensas de monstruos. Embárcate en una épica aventura en un mundo de fantasía devastado por la guerra.',
                'developer' => 'CD Projekt Red',
                'publisher' => 'CD Projekt',
                'price' => 9.99,
                'genres' => ['RPG', 'Action', 'Open World'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox', 'Nintendo Switch'],
                'release_date' => '2015-05-19',
                'metacritic_score' => 93,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/292030/header.jpg',
            ],
            [
                'title' => 'Elden Ring',
                'description' => 'Adéntrate en las Tierras Intermedias y enfréntate a los semidioses en este RPG de acción de mundo abierto creado por FromSoftware y George R.R. Martin.',
                'developer' => 'FromSoftware',
                'publisher' => 'Bandai Namco',
                'price' => 54.99,
                'genres' => ['RPG', 'Action', 'Souls-like'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox'],
                'release_date' => '2022-02-25',
                'metacritic_score' => 95,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg',
            ],
            [
                'title' => 'Red Dead Redemption 2',
                'description' => 'Vive la historia de Arthur Morgan en el salvaje oeste americano.',
                'developer' => 'Rockstar Games',
                'publisher' => 'Rockstar Games',
                'price' => 29.99,
                'genres' => ['Action', 'Adventure', 'Open World'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox'],
                'release_date' => '2019-11-05',
                'metacritic_score' => 97,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg',
            ],
            [
                'title' => 'God of War',
                'description' => 'Kratos y Atreus emprenden un viaje épico inspirado en la mitología nórdica.',
                'developer' => 'Santa Monica Studio',
                'publisher' => 'Sony Interactive Entertainment',
                'price' => 49.99,
                'genres' => ['Action', 'Adventure'],
                'platforms' => ['Windows', 'PlayStation'],
                'release_date' => '2022-01-14',
                'metacritic_score' => 94,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1593500/header.jpg',
            ],
            [
                'title' => 'Hades',
                'description' => 'Escapa del inframundo en este frenético roguelike inspirado en la mitología griega.',
                'developer' => 'Supergiant Games',
                'publisher' => 'Supergiant Games',
                'price' => 19.99,
                'genres' => ['Rogue-like', 'Action', 'Indie'],
                'platforms' => ['Windows', 'Nintendo Switch', 'PlayStation', 'Xbox'],
                'release_date' => '2020-09-17',
                'metacritic_score' => 93,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1145360/header.jpg',
            ],
            [
                'title' => 'Minecraft',
                'description' => 'Construye, explora y sobrevive en un mundo generado proceduralmente.',
                'developer' => 'Mojang Studios',
                'publisher' => 'Xbox Game Studios',
                'price' => 26.95,
                'genres' => ['Sandbox', 'Survival', 'Adventure'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox', 'Nintendo Switch'],
                'release_date' => '2011-11-18',
                'metacritic_score' => 93,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1672970/header.jpg',
            ],
            [
                'title' => 'Baldur\'s Gate 3',
                'description' => 'Un RPG basado en Dungeons & Dragons con enormes posibilidades narrativas.',
                'developer' => 'Larian Studios',
                'publisher' => 'Larian Studios',
                'price' => 59.99,
                'genres' => ['RPG', 'Strategy', 'Turn-Based'],
                'platforms' => ['Windows', 'PlayStation'],
                'release_date' => '2023-08-03',
                'metacritic_score' => 96,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1086940/header.jpg',
            ],
            [
                'title' => 'DOOM Eternal',
                'description' => 'Destruye demonios en este shooter frenético y brutal.',
                'developer' => 'id Software',
                'publisher' => 'Bethesda Softworks',
                'price' => 39.99,
                'genres' => ['FPS', 'Action'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox', 'Nintendo Switch'],
                'release_date' => '2020-03-20',
                'metacritic_score' => 88,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/782330/header.jpg',
            ],
            [
                'title' => 'Resident Evil 4',
                'description' => 'Leon S. Kennedy debe rescatar a la hija del presidente en un pueblo infectado por una amenaza biológica.',
                'developer' => 'Capcom',
                'publisher' => 'Capcom',
                'price' => 59.99,
                'genres' => ['Survival Horror', 'Action'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox'],
                'release_date' => '2023-03-24',
                'metacritic_score' => 93,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2050650/header.jpg',
            ],
            [
                'title' => 'Sekiro: Shadows Die Twice',
                'description' => 'Domina el combate samurái en esta desafiante aventura de acción de FromSoftware.',
                'developer' => 'FromSoftware',
                'publisher' => 'Activision',
                'price' => 49.99,
                'genres' => ['Action', 'Souls-like', 'Adventure'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox'],
                'release_date' => '2019-03-22',
                'metacritic_score' => 90,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/814380/header.jpg',
            ],
            [
                'title' => 'Hollow Knight',
                'description' => 'Explora un reino subterráneo lleno de secretos y enemigos en este metroidvania indie.',
                'developer' => 'Team Cherry',
                'publisher' => 'Team Cherry',
                'price' => 14.99,
                'genres' => ['Metroidvania', 'Indie', 'Action'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox', 'Nintendo Switch'],
                'release_date' => '2017-02-24',
                'metacritic_score' => 90,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/367520/header.jpg',
            ],
            [
                'title' => 'Starfield',
                'description' => 'Explora el espacio y descubre nuevos mundos en el RPG espacial de Bethesda.',
                'developer' => 'Bethesda Game Studios',
                'publisher' => 'Bethesda Softworks',
                'price' => 69.99,
                'genres' => ['RPG', 'Sci-Fi', 'Open World'],
                'platforms' => ['Windows', 'Xbox'],
                'release_date' => '2023-09-06',
                'metacritic_score' => 83,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1716740/header.jpg',
            ],
            [
                'title' => 'Dead Cells',
                'description' => 'Un roguelite de acción rápida con combate desafiante y niveles procedurales.',
                'developer' => 'Motion Twin',
                'publisher' => 'Motion Twin',
                'price' => 24.99,
                'genres' => ['Rogue-like', 'Metroidvania', 'Action'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox', 'Nintendo Switch'],
                'release_date' => '2018-08-07',
                'metacritic_score' => 89,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/588650/header.jpg',
            ],
            [
                'title' => 'Control',
                'description' => 'Descubre los secretos de una agencia paranormal en este shooter sobrenatural.',
                'developer' => 'Remedy Entertainment',
                'publisher' => '505 Games',
                'price' => 29.99,
                'genres' => ['Action', 'Sci-Fi', 'Adventure'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox'],
                'release_date' => '2019-08-27',
                'metacritic_score' => 85,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/870780/header.jpg',
            ],
            [
                'title' => 'Forza Horizon 5',
                'description' => 'Conduce por México en uno de los juegos de conducción más espectaculares.',
                'developer' => 'Playground Games',
                'publisher' => 'Xbox Game Studios',
                'price' => 59.99,
                'genres' => ['Racing', 'Open World'],
                'platforms' => ['Windows', 'Xbox'],
                'release_date' => '2021-11-09',
                'metacritic_score' => 92,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg',
            ],
            [
                'title' => 'Persona 5 Royal',
                'description' => 'Vive una doble vida como estudiante y ladrón fantasma en este JRPG aclamado.',
                'developer' => 'Atlus',
                'publisher' => 'SEGA',
                'price' => 59.99,
                'genres' => ['JRPG', 'Anime', 'Turn-Based'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox', 'Nintendo Switch'],
                'release_date' => '2022-10-21',
                'metacritic_score' => 95,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1687950/header.jpg',
            ],
            [
                'title' => 'Monster Hunter: World',
                'description' => 'Caza enormes criaturas en un ecosistema vivo lleno de desafíos.',
                'developer' => 'Capcom',
                'publisher' => 'Capcom',
                'price' => 29.99,
                'genres' => ['Action', 'RPG', 'Co-op'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox'],
                'release_date' => '2018-08-09',
                'metacritic_score' => 90,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/582010/header.jpg',
            ],
            [
                'title' => 'Disco Elysium',
                'description' => 'Resuelve un asesinato en este RPG narrativo con profundas decisiones morales.',
                'developer' => 'ZA/UM',
                'publisher' => 'ZA/UM',
                'price' => 39.99,
                'genres' => ['RPG', 'Detective', 'Indie'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox', 'Nintendo Switch'],
                'release_date' => '2019-10-15',
                'metacritic_score' => 91,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/632470/header.jpg',
            ],
            [
                'title' => 'Dark Souls III',
                'description' => 'Enfréntate a poderosos enemigos y explora un oscuro mundo en ruinas.',
                'developer' => 'FromSoftware',
                'publisher' => 'Bandai Namco',
                'price' => 39.99,
                'genres' => ['RPG', 'Souls-like', 'Action'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox'],
                'release_date' => '2016-04-12',
                'metacritic_score' => 89,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/374320/header.jpg',
            ],
            [
                'title' => 'Celeste',
                'description' => 'Ayuda a Madeline a escalar la montaña Celeste en este desafiante plataformas indie.',
                'developer' => 'Matt Makes Games',
                'publisher' => 'Extremely OK Games',
                'price' => 19.99,
                'genres' => ['Platformer', 'Indie'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox', 'Nintendo Switch'],
                'release_date' => '2018-01-25',
                'metacritic_score' => 92,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/504230/header.jpg',
            ],
            [
                'title' => 'Death Stranding',
                'description' => 'Reconecta una sociedad fragmentada en esta experiencia única creada por Hideo Kojima.',
                'developer' => 'Kojima Productions',
                'publisher' => '505 Games',
                'price' => 39.99,
                'genres' => ['Adventure', 'Open World', 'Sci-Fi'],
                'platforms' => ['Windows', 'PlayStation'],
                'release_date' => '2020-07-14',
                'metacritic_score' => 86,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1190460/header.jpg',
            ],
            [
                'title' => 'The Last of Us Part I',
                'description' => 'Acompaña a Joel y Ellie en un emotivo viaje en un mundo postapocalíptico.',
                'developer' => 'Naughty Dog',
                'publisher' => 'Sony Interactive Entertainment',
                'price' => 59.99,
                'genres' => ['Action', 'Adventure', 'Survival'],
                'platforms' => ['Windows', 'PlayStation'],
                'release_date' => '2023-03-28',
                'metacritic_score' => 88,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1888930/header.jpg',
            ],
            [
                'title' => 'Nier: Automata',
                'description' => 'Lucha junto a androides en una guerra contra máquinas en este RPG de acción.',
                'developer' => 'PlatinumGames',
                'publisher' => 'Square Enix',
                'price' => 39.99,
                'genres' => ['Action', 'RPG', 'Sci-Fi'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox'],
                'release_date' => '2017-03-17',
                'metacritic_score' => 88,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/524220/header.jpg',
            ],
            [
                'title' => 'Ori and the Will of the Wisps',
                'description' => 'Descubre un hermoso mundo lleno de magia y peligros en esta aventura de plataformas.',
                'developer' => 'Moon Studios',
                'publisher' => 'Xbox Game Studios',
                'price' => 29.99,
                'genres' => ['Metroidvania', 'Adventure', 'Platformer'],
                'platforms' => ['Windows', 'Xbox', 'Nintendo Switch'],
                'release_date' => '2020-03-11',
                'metacritic_score' => 90,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1057090/header.jpg',
            ],
            [
                'title' => 'Assassin\'s Creed Valhalla',
                'description' => 'Conquista Inglaterra como un guerrero vikingo en esta épica aventura histórica.',
                'developer' => 'Ubisoft Montreal',
                'publisher' => 'Ubisoft',
                'price' => 49.99,
                'genres' => ['Action', 'RPG', 'Open World'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox'],
                'release_date' => '2020-11-10',
                'metacritic_score' => 84,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2208920/header.jpg',
            ],
            [
                'title' => 'Subnautica',
                'description' => 'Sobrevive y explora un misterioso océano alienígena lleno de criaturas increíbles.',
                'developer' => 'Unknown Worlds Entertainment',
                'publisher' => 'Krafton',
                'price' => 29.99,
                'genres' => ['Survival', 'Adventure', 'Open World'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox', 'Nintendo Switch'],
                'release_date' => '2018-01-23',
                'metacritic_score' => 87,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/264710/header.jpg',
            ],
            [
                'title' => 'Street Fighter 6',
                'description' => 'La legendaria saga de lucha regresa con nuevos modos y mecánicas renovadas.',
                'developer' => 'Capcom',
                'publisher' => 'Capcom',
                'price' => 59.99,
                'genres' => ['Fighting', 'Competitive'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox'],
                'release_date' => '2023-06-02',
                'metacritic_score' => 92,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1364780/header.jpg',
            ],
            [
                'title' => 'Cuphead',
                'description' => 'Un desafiante juego de acción y plataformas con estética de dibujos animados clásicos.',
                'developer' => 'Studio MDHR',
                'publisher' => 'Studio MDHR',
                'price' => 19.99,
                'genres' => ['Platformer', 'Action', 'Indie'],
                'platforms' => ['Windows', 'PlayStation', 'Xbox', 'Nintendo Switch'],
                'release_date' => '2017-09-29',
                'metacritic_score' => 87,
                'cover_image' => 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/268910/header.jpg',
            ],
        ];

        foreach ($games as $game) {
            Game::create($game);
        }
    }
}
